
REST_PROTOCOL = "http://"
SOCKET_PROTOCOL = "ws://"
BASE_URL = "localhost:8080"

REST_BASE_URL = REST_PROTOCOL + BASE_URL
SOCKET_BASE_URL = SOCKET_PROTOCOL + BASE_URL

SLEEP_TIME = 5
ONE_COMMIT_CLICK = 5
STATUS_CHECK_INTERVAL = 3
STUCK_CHECK_INTERVAL = 3
MAX_FAILED_ATTEMPTS = 3